title: Mehdi
description: Senior DevOps
url: "https://me.podpacer.cc"
 
theme: minima
minima:
  skin: dark
 
plugins:
  - jekyll-seo-tag
 
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
 
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
 