title: Mehdi JAQIR-GRANGER
description: Senior DevOps / Platform Engineer
url: "https://me.podpacer.cc"

theme: minima
minima:
  skin: dark

plugins:
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
